name: Deploy to Azure Web App

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Construir aplicación
        run: npm run build

      - name: Desplegar en Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          app-name: "tu-app-name"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          action: "upload"
          app_location: "/"
